- contracts/Ingress.sol
- test/test-ingress.js
* Updated ingress with expected behaviour
* Created unit test for it
* Renamed the contract variables throughout the test to improve readability
> PAN-2557: Ingress reject any connection until bootstrapped

- README.md
> Updated contact link 

- contracts/NodeIngress.sol
- contracts/Rules.sol
- migrations/2_deploy_ingress_rules_contract.js
- test/test-node-ingress-proxy.js
- test/test-node-ingress.js
- test/test-node-rules-permissioning.js
- test/test-node-rules-read-only-mode.js
Making way for the account ingress contract to be added
> Renamed existing Ingress to NodeIngress

- package-lock.json
https://github.com/PegaSysEng/permissioning-smart-contracts/network/alert/package-lock.json/handlebars/open
> Bump handlebars from 4.1.1 to 4.1.2

- src/App.test.tsx
- src/context/__test__/configData.test.tsx
- src/context/__test__/network.test.tsx
- src/context/adminData.tsx
- src/context/configData.tsx
- src/context/network.tsx
- src/drizzleOptions.ts
Moves creation of drizzle context from import time to mount time to allow for configuration
> [OP-15] creation of drizzle at time of provider creation

- src/components/AccountTab/AccountTab.tsx
- src/components/AdminTab/AdminTab.tsx
- src/components/Dashboard/__test__/__snapshots__/Dashboard.test.tsx.snap
- src/components/Dashboard/__test__/__snapshots__/TabSelector.test.tsx.snap
- src/components/Modals/Add.tsx
- src/components/Modals/Lock.tsx
- src/components/Modals/Remove.tsx
- src/constants/modals.ts
- src/containers/Modals/Add.tsx
- src/containers/Modals/Remove.tsx
> modal components to tsx

- src/containers/Tabs/Account.tsx
check for duplicate accounts before adding
> [OP-42] added check for duplicate account when adding to whitelist

- src/components/AdminTab/TableHeader.tsx
- src/components/Dashboard/__test__/__snapshots__/Dashboard.test.tsx.snap
- src/components/Dashboard/__test__/__snapshots__/TabSelector.test.tsx.snap
- src/constants/tabs.ts
Admin Accounts changed to Admins; changed order of tabs
> [OP-45] changed text for Admins tab; moved to the right

- src/context/accountData.tsx
- src/context/nodeData.tsx
Accounts and nodes now refresh on contract events
> [op-46] [op-15] listen contract events

- .yarnrc
- Jenkinsfile
- Jenkinsfile.release
- src/containers/Layout/__test__/Initializer.test.tsx
Version bumping, tagging, artefact creation. I'll add docker in a followup PR
> [OP-62] release job

- README.md
deployment instructions in the readme
> [OP-63] Added deployment instructions

- src/chain/provider.ts
Context: https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8
> Fix metamask load

- README.md
> Updated readme details

- README.md
Added deployment details and small tidy up. Also added notes on Windows support.
> updated deployment steps in README

- src/containers/Tabs/Account.tsx
- src/containers/Tabs/Admin.tsx
- src/containers/Tabs/Enode.tsx
the raw gas limit for removal txs is too low, need to set it higher
> set a higher gas limit for removal txs

- src/chain/provider.ts
- src/context/adminData.tsx
update the account when user changes it in Metamask
> add polling to provider and update user account

- contracts/AccountRules.sol
- contracts/NodeRules.sol
added comments to make usage clear
> clarify readOnlyMode usage

- contracts/Ingress.sol
- test/test-node-ingress.js
revert changes to Ingress contract
> Revert changes to Ingress

- contracts/Ingress.sol
> [OP-81] fixed compiler

- contracts/AccountIngress.sol
- contracts/Ingress.sol
- contracts/NodeIngress.sol
just use address instead since owner field was unused
> [OP-82] remove ContractDetails struct 

- contracts/Ingress.sol
code style recommendation from audit
> changed to 0 for bytes 0

- README.md
> Added license note

- contracts/AccountRules.sol
- contracts/AccountRulesList.sol
- contracts/Admin.sol
- contracts/AdminList.sol
- contracts/NodeRules.sol
- contracts/NodeRulesList.sol
- test/test-account-rules-list.js
- test/test-account-rules-permissioning.js
- test/test-admin.js
- test/test-node-rules-list.js
- test/test-node-rules-permissioning.js
Use "allowlist" or "permitted" instead
> remove use of whitelist in contracts

- src/components/AccountTab/EmptyRow.tsx
- src/components/AccountTab/TableHeader.tsx
- src/components/Dashboard/__test__/__snapshots__/Dashboard.test.tsx.snap
- src/components/Dashboard/__test__/__snapshots__/TabSelector.test.tsx.snap
- src/components/EnodeTab/EmptyRow.tsx
- src/components/EnodeTab/TableHeader.tsx
- src/constants/modals.ts
- src/constants/tabs.ts
- src/containers/Tabs/Account.tsx
- src/containers/Tabs/Enode.tsx
- test/test-admin.js
> changed UI to use "permitted" instead of "whitelist"

- src/containers/Tabs/Account.tsx
- src/containers/Tabs/Enode.tsx
- src/context/accountData.tsx
- src/context/adminData.tsx
- src/context/nodeData.tsx
> rename whitelist in backend of dapp

- genesis.json
use chain id 2018 rather than 999
> [MINOR] use same chainId as other examples

- README.md
- migrations/2_deploy_admin_contract.js
- migrations/3_deploy_node_ingress_rules_contract.js
- migrations/4_deploy_account_ingress_rules_contract.js
- scripts/allowlist_utils.js
add the option to retain existing rules contacts x 3
> Allow separate deployments

- .circleci/config.yml
Signed-off-by: Lucas Saldanha <lucascrsaldanha@gmail.com>
> Added Mythx workflow step

- contracts/AccountRulesList.sol
- contracts/AdminList.sol
- contracts/NodeRulesList.sol
I've spoken with Mythx and in our case it is ok to ignore this warning.
> Fix Mythx false alarms

- contracts/NodeRulesList.sol
The comment should be placed on the same line as the reported issue.
> fix mythx disable comment

- README.md
- migrations/2_deploy_admin_contract.js
- scripts/allowlist_utils.js
Fixed bug in processing RETAIN_* environment variables. 
Update readme to match code. This was renamed some time ago.
> fixed bug in processing environment variables

- src/components/Dashboard/__test__/__snapshots__/Dashboard.test.tsx.snap
- src/components/Dashboard/__test__/__snapshots__/TabSelector.test.tsx.snap
- yarn.lock
> upgraded dependencies

- contracts/AccountRulesList.sol
one high severity warning worth dealing with
> moved comment to disable mythx warning

- contracts/ExposedNodeRulesList.sol
- contracts/NodeRules.sol
This will fix most of the Mythx `moderate` warnings and has no effect on functionality
> make functions external where possible

- CONTRIBUTING.md
> [MINOR] updated repo links

- genesis.json
This has been changed elsewhere in samples - besu, web3js-eea
> [MINOR] update chainId in example genesis

- README.md
> added link to audit and some headings

- README.md
> README - changed order and wording

- README.md
> updated license wording

- .circleci/config.yml
- contracts/AccountIngress.sol
- contracts/AccountRules.sol
- contracts/Admin.sol
- contracts/ExposedAccountRulesList.sol
- contracts/ExposedAdminList.sol
- contracts/Ingress.sol
- contracts/NodeIngress.sol
- contracts/NodeRules.sol
mostly regarding visibility of functions
> Address mythx warnings

- contracts/AccountRules.sol
- contracts/Ingress.sol
> more mythx including ignoring one that can't be fixed

- migrations/2_deploy_admin_contract.js
- migrations/3_deploy_node_ingress_rules_contract.js
- migrations/4_deploy_account_ingress_rules_contract.js
> add logging for lists as they are deployed and even if they aren't

- contracts/AccountRules.sol
- test/test-account-rules-permissioning.js
> Allow admin accounts to send transactions

- test/test-account-rules-permissioning.js
> test removeAccount

- yarn.lock
See #263 
This one was created from dependabot auto-generated PR #268
> bump follow-redirects as per dependabot

- yarn.lock
See #263 
This one was created by dependabot PR #269
> bump shelljs as per dependabot suggestion

- yarn.lock
> truffle/hdwallet-provider 1.7.0
